### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by culka**
Initial setup with docker-compose setup and an example API interface and repository

Resolves HSLdevcom/jore4#1334

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 6 of 20 files at r1, 1 of 13 files at r5, 2 of 8 files at r7, 1 of 15 files at r9, 1 of 1 files at r10, 5 of 8 files at r11, 5 of 7 files at r12, 2 of 9 files at r13, 9 of 9 files at r14, 3 of 136 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 25 of 158 files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`Dockerfile` line 14 at r15](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NcvK-reC0Fk471awr38:-NcvK-reC0Fk471awr39:b-9x6ecf) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6348db5591164aeb1fa486f9cba2dc14ff2fa8d9/Dockerfile#L14)):*
> ```Dockerfile
> 
> # generate jOOQ classes using "dev" profile
> COPY ./profiles/dev/config.properties /build/profiles/dev/config.properties
> ```

jOOQ classes do not need to be generated within Docker image build. Remove this section! Basically you can revert my previous changes except for JRE version.
___
*[`Dockerfile` line 20 at r15](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NcvKEOt2EJuggVs83Y3:-NcvKEOt2EJuggVs83Y4:bx1hrm) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6348db5591164aeb1fa486f9cba2dc14ff2fa8d9/Dockerfile#L20)):*
> ```Dockerfile
> # package using "prod" profile
> COPY ./profiles/prod /build/profiles/prod
> RUN mvn -Pprod package spring-boot:repackage
> ```

Replace this line by adding `clean`. =>

```
# build using "prod" profile
COPY ./profiles/prod /build/profiles/prod
RUN mvn -Pprod clean package spring-boot:repackage
```
___
*[`pom.xml` line 89 at r15](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NcvKd494eoPYsaOVApR:-NcvKd494eoPYsaOVApS:b-fyetg8) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6348db5591164aeb1fa486f9cba2dc14ff2fa8d9/pom.xml#L89)):*
> ```XML
>                 <build.property.file>profiles/${build.profile.id}/config.properties</build.property.file>
>                 <build.property.user-override.file>profiles/${build.profile.id}/config.${user.name}.properties</build.property.user-override.file>
>                 <skip.jooq.generation>true</skip.jooq.generation>
> ```

IMO after adding jOOQ classes to the repository, this could be changed to false.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 25 of 158 files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`Dockerfile` line 14 at r15](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NcvK-reC0Fk471awr38:-NcxJ-SD9DJmzlD5xIKS:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6348db5591164aeb1fa486f9cba2dc14ff2fa8d9/Dockerfile#L14)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

jOOQ classes do not need to be generated within Docker image build. Remove this section! Basically you can revert my previous changes except for JRE version.
</blockquote></details>

Done.
___
*[`Dockerfile` line 20 at r15](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NcvKEOt2EJuggVs83Y3:-NcxR4qN45m1oTKulizv:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6348db5591164aeb1fa486f9cba2dc14ff2fa8d9/Dockerfile#L20)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Replace this line by adding `clean`. =>

```
# build using "prod" profile
COPY ./profiles/prod /build/profiles/prod
RUN mvn -Pprod clean package spring-boot:repackage
```
</blockquote></details>

Done.
___
*[`pom.xml` line 89 at r15](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NcvKd494eoPYsaOVApR:-NcxR9Y2AnbJqKsHjfhO:b5nev1e) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6348db5591164aeb1fa486f9cba2dc14ff2fa8d9/pom.xml#L89)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO after adding jOOQ classes to the repository, this could be changed to false.
</blockquote></details>

I'm not sure if we want to generate them each run. There still is the command on `development.sh` to generate the jOOQ classes.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 136 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 27 of 158 files reviewed, 7 unresolved discussions (waiting on @culka)

___
*[`Dockerfile` line 23 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4ABBGA2vDY68LW4Jt:-Nd4ABBGA2vDY68LW4Ju:b-luitza) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/Dockerfile#L23)):*
> ```Dockerfile
> 
> # download script for reading Docker secrets
> RUN curl -o /tmp/lread-secrets.sh "https://raw.githubusercontent.com/HSLdevcom/jore4-tools/main/docker/read-secrets.sh"
> ```

You changed `read-secrets.sh` to `lread-secrets.sh`. Please revert it.
___
*[`pom.xml` line 89 at r15](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NcvKd494eoPYsaOVApR:-Nd4BLWBBXCHaI5fs8sd:btplo8e) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6348db5591164aeb1fa486f9cba2dc14ff2fa8d9/pom.xml#L89)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

I'm not sure if we want to generate them each run. There still is the command on `development.sh` to generate the jOOQ classes.
</blockquote></details>

Ok. On my machine it only takes less than 2 seconds to generate the jOOQ classes during the Maven build, but we can leave it off if you like it better.

However, if you omit it, you should add notes to `README.md` that sometimes (under which circumstances) the code generation needs to be executed manually.
___
*[`pom.xml` line 9 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4ApcZEAPEhbkayyQz:-Nd4ApcZEAPEhbkayyR-:br2nyll) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L9)):*
> ```XML
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-parent</artifactId>
>         <version>3.1.2</version>
> ```

ATM `3.1.3` is the most recent Spring Boot release.
___
*[`pom.xml` line 321 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4CnCv8KWuYaaBSz4z:-Nd4CnCv8KWuYaaBSz5-:bgkop13) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L321)):*
> ```XML
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-compiler-plugin</artifactId>
>                 <version>3.8.1</version>
> ```

IMO it is safe to raise the versions of this plugin to `3.11.0` (the most recent ATM).
___
*[`pom.xml` line 423 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4s0PV9uYyH92iqtwq:-Nd4s0PW9ql-hqzNw_tw:b1bcngu) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L423)):*
> ```XML
>                                         | SKEYS
>                                         | SVALS
>                                         | EACH
> ```

I think you should add `information_schema.*` here because there are many classes generated from this schema that we probably don't need.
___
*[`pom.xml` line 430 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4EOgM7yIlDSkLeRyR:-Nd4EOgM7yIlDSkLeRyS:b-zdha9v) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L430)):*
> ```XML
>                                     <includeInvisibleColumns>false</includeInvisibleColumns>
>                                     <includeEmbeddables>false</includeEmbeddables>
>                                     <includeRoutines>true</includeRoutines>
> ```

Not sure whether `includeRoutines=true` is really needed but this makes our custom SQL functions available in types Kotlin code.
___
*[`pom.xml` line 439 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4E_jB50_jfq45hcQ_:-Nd4E_jB50_jfq45hcQa:b-o6obud) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L439)):*
> ```XML
>                                     <includeSequences>false</includeSequences>
>                                     <includePrimaryKeys>false</includePrimaryKeys>
>                                     <includeUniqueKeys>false</includeUniqueKeys>
> ```

I think it would be preferable to change the following to `true`.

- `includeSequences`
- `includePrimaryKeys`
- `includeForeignKeys`

Maybe also:
- `includeUniqueKeys`

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 14 of 171 files reviewed, 7 unresolved discussions (waiting on @jarkkoka)

___
*[`Dockerfile` line 23 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4ABBGA2vDY68LW4Jt:-NdTzQo008O81OdMdoMO:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/Dockerfile#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You changed `read-secrets.sh` to `lread-secrets.sh`. Please revert it.
</blockquote></details>

Done.
___
*[`pom.xml` line 9 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4ApcZEAPEhbkayyQz:-NdTzRfL0EGTeCOXCd8G:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L9)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

ATM `3.1.3` is the most recent Spring Boot release.
</blockquote></details>

Done.
___
*[`pom.xml` line 321 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4CnCv8KWuYaaBSz4z:-NdU-8QZ4h0wKceqmJjU:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L321)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO it is safe to raise the versions of this plugin to `3.11.0` (the most recent ATM).
</blockquote></details>

Done.
___
*[`pom.xml` line 423 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4s0PV9uYyH92iqtwq:-NdU-9UmBTvTqlv0BZMi:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L423)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think you should add `information_schema.*` here because there are many classes generated from this schema that we probably don't need.
</blockquote></details>

Done.
___
*[`pom.xml` line 430 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4EOgM7yIlDSkLeRyR:-NdU-DDsE--NkcVke7kl:bgeyugt) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L430)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Not sure whether `includeRoutines=true` is really needed but this makes our custom SQL functions available in types Kotlin code.
</blockquote></details>

This has been requested
___
*[`pom.xml` line 439 at r16](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Nd4E_jB50_jfq45hcQ_:-NdU-Q_v9jstc_SxN5-F:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/7a1ee73225220094de5bdc3cb5cc6f590211b643/pom.xml#L439)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think it would be preferable to change the following to `true`.

- `includeSequences`
- `includePrimaryKeys`
- `includeForeignKeys`

Maybe also:
- `includeUniqueKeys`
</blockquote></details>

Done.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 141 files at r17, 211 of 211 files at r18, 1 of 1 files at r20, 4 of 142 files at r21, 1 of 211 files at r22, 5 of 5 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 19 of 230 files reviewed, 6 unresolved discussions (waiting on @culka)

___
*[`.github/workflows/check-renovatebot-config.yml` line 9 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVPqdz47TaQ4zx_EFp:-NdVPqe-Buf1az5q0n-v:b-nlxif4) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/check-renovatebot-config.yml#L9)):*
> ```YAML
>   validate:
>     name: Validate renovatebot config
>     runs-on: ubuntu-20.04
> ```

IMO `ubuntu-22.04` should be chosen nowadays.
___
*[`.github/workflows/docker-build.yml` line 13 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVPzqJ2AP4teYpn3o7:-NdVPzqJ2AP4teYpn3o8:bu3cufz) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/docker-build.yml#L13)):*
> ```YAML
>   push_to_registry:
>     name: Build & Push docker image to Docker Hub
>     runs-on: ubuntu-20.04
> ```

IMO `ubuntu-22.04` should be used
___
*[`.github/workflows/run-cypress-tests.yml` line 11 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVQ7WG2I_pp18VvaQ_:-NdVQ7WG2I_pp18VvaQa:b-bqmfzj) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/run-cypress-tests.yml#L11)):*
> ```YAML
>   run_cypress_tests:
>     name: Run cypress e2e tests from docker
>     runs-on: ubuntu-20.04
> ```

ubuntu-22.04
___
*[`.github/workflows/run-cypress-tests.yml` line 30 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVQAUr5y-j3fTBYGkH:-NdVQAUr5y-j3fTBYGkI:b-ug3iyl) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/run-cypress-tests.yml#L30)):*
> ```YAML
>         with:
>           hastus_version: "${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}"
>       
> ```

unnecessary space characters after newline
___
*[`.github/workflows/run-cypress-tests.yml` line 35 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVQSD4EmfvAs_WuvCn:-NdVQSD4EmfvAs_WuvCo:b-1k8ygo) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/run-cypress-tests.yml#L35)):*
> ```YAML
> 
>       - name: Run e2e tests from github action
>         uses: HSLdevcom/jore4-tools/github-actions/run-cypress-tests@run-cypress-tests-v1
> ```

I think the more recent `run-cypress-tests-v2` should be used,

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 15 of 230 files reviewed, 6 unresolved discussions (waiting on @jarkkoka)

___
*[`.github/workflows/check-renovatebot-config.yml` line 9 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVPqdz47TaQ4zx_EFp:-NdVk1W_26c195FNlGzH:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/check-renovatebot-config.yml#L9)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO `ubuntu-22.04` should be chosen nowadays.
</blockquote></details>

Done.
___
*[`.github/workflows/docker-build.yml` line 13 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVPzqJ2AP4teYpn3o7:-NdVk28mDTXihOyfde-R:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/docker-build.yml#L13)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO `ubuntu-22.04` should be used
</blockquote></details>

Done.
___
*[`.github/workflows/run-cypress-tests.yml` line 11 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVQ7WG2I_pp18VvaQ_:-NdVk3bb304gHJ-4UHpY:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/run-cypress-tests.yml#L11)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

ubuntu-22.04
</blockquote></details>

Done.
___
*[`.github/workflows/run-cypress-tests.yml` line 30 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVQAUr5y-j3fTBYGkH:-NdVlNFI4ntkbdc9MrKK:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/run-cypress-tests.yml#L30)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

unnecessary space characters after newline
</blockquote></details>

Done.
___
*[`.github/workflows/run-cypress-tests.yml` line 35 at r23](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdVQSD4EmfvAs_WuvCn:-NdVlQ4Y5MlZo5TNmXSZ:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e6f90b01c7e253c77b5e98322d41f48ce5dc091e/.github/workflows/run-cypress-tests.yml#L35)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think the more recent `run-cypress-tests-v2` should be used,
</blockquote></details>

Done.

**Review by jarkkoka — COMMENTED** [review]
Basically :lgtm: but some GitHub workflows still fail.

> Reviewed 2 of 142 files at r21, 6 of 211 files at r22, 4 of 4 files at r24.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-:-NdZIS2-45LkkOiduW_T:b-x2wm6x)* status: 27 of 230 files reviewed, 1 unresolved discussion (waiting on @culka)

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 27 of 230 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`.github/workflows/run-cypress-tests.yml` line 13 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdZRbJh90mJDwBTTH81:-NdZRbJh90mJDwBTTH82:bxpg352) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/18559ebba12e47be9a42a9a4d3b552fc4369c1cb/.github/workflows/run-cypress-tests.yml#L13)):*
> ```YAML
>     runs-on: ubuntu-22.04
> 
>       - name: Checkout code
> ```

You need to add `steps:` keyword before `- name: Checkout code`

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 27 of 230 files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`.github/workflows/test-docker-compose.yml` line 11 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdZSl7i3g8y2Fx0afXi:-NdZSl7i3g8y2Fx0afXj:b8pl4x6) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/18559ebba12e47be9a42a9a4d3b552fc4369c1cb/.github/workflows/test-docker-compose.yml#L11)):*
> ```YAML
>   test-docker-compose:
>     name: verify docker-compose setup
>     runs-on: ubuntu-20.04
> ```

Change `20` to `22` here (Ubuntu version).

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 24 of 230 files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`pom.xml` line 89 at r15](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NcvKd494eoPYsaOVApR:-Nd_BcdWBVPd93ml7g2S:bhcmvrs) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/6348db5591164aeb1fa486f9cba2dc14ff2fa8d9/pom.xml#L89)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok. On my machine it only takes less than 2 seconds to generate the jOOQ classes during the Maven build, but we can leave it off if you like it better.

However, if you omit it, you should add notes to `README.md` that sometimes (under which circumstances) the code generation needs to be executed manually.
</blockquote></details>

Added mention to readme
___
*[`.github/workflows/run-cypress-tests.yml` line 13 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdZRbJh90mJDwBTTH81:-Nd_C5RH9htA1_W248bS:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/18559ebba12e47be9a42a9a4d3b552fc4369c1cb/.github/workflows/run-cypress-tests.yml#L13)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You need to add `steps:` keyword before `- name: Checkout code`
</blockquote></details>

Done.
___
*[`.github/workflows/test-docker-compose.yml` line 11 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdZSl7i3g8y2Fx0afXi:-Nd_C8GD2ey3x0mI2YBT:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/18559ebba12e47be9a42a9a4d3b552fc4369c1cb/.github/workflows/test-docker-compose.yml#L11)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Change `20` to `22` here (Ubuntu version).
</blockquote></details>

Done.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 211 files at r22, 3 of 3 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 28 of 230 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`.github/workflows/run-cypress-tests.yml` line 23 at r25](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdenqS-22jQfSAbhvdz:-NdenqS0Bn3CiIRZeMqf:b-7vjge8) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/276f4afb7d8fc15779ebb5d3f90dfedc53bc2d75/.github/workflows/run-cypress-tests.yml#L23)):*
> ```YAML
>         uses: HSLdevcom/jore4-tools/github-actions/setup-e2e-environment@setup-e2e-environment-v1
>         with:
>           hastus_version: "${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}"
> ```

You have a bug here. You are trying to fetch `jore4-hastus` image from Docker hub using `jore4-timetables-api`'s image name and commit ID.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 27 of 230 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`.github/workflows/run-cypress-tests.yml` line 23 at r25](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-NdenqS-22jQfSAbhvdz:-NdiKxtQ4xce-Lg42IA9:bl4uhcm) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/276f4afb7d8fc15779ebb5d3f90dfedc53bc2d75/.github/workflows/run-cypress-tests.yml#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You have a bug here. You are trying to fetch `jore4-hastus` image from Docker hub using `jore4-timetables-api`'s image name and commit ID.
</blockquote></details>

Too much copy paste config...

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 27 of 230 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`.github/workflows/test-docker-compose.yml` line 10 at r27](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Ndjozyq1F-EyGiZr5Je:-Ndjozyq1F-EyGiZr5Jf:b1h0p80) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/74ca7e8ce654c8cc85bbda1928925b42d4e83bad/.github/workflows/test-docker-compose.yml#L10)):*
> ```YAML
> env:
>   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```

This not required in `jore4-map-matching` repository. Are you sure this is really needed?

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 25 of 230 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`.github/workflows/test-docker-compose.yml` line 10 at r27](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2#-Ndjozyq1F-EyGiZr5Je:-NdkF5386885j-s6o6AR:b-bzbdc7) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/74ca7e8ce654c8cc85bbda1928925b42d4e83bad/.github/workflows/test-docker-compose.yml#L10)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This not required in `jore4-map-matching` repository. Are you sure this is really needed?
</blockquote></details>

It is needed for github authentication

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r27, 2 of 2 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/2)* status: 28 of 230 files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
