### PR TITLE
Use different data inserter user

### PR DESCRIPTION
**Pull request by culka**
Use the Hasura database user for data inserter, due to the timetables-api user not having truncate privileges.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13)* status: all files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/config/TestDatabaseProperties.kt` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13#-Nh622o63BSSHyR3_LCz:-Nh622o63BSSHyR3_LD-:b9wqrr1) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/a195b3bc9d74117a7d4403daec62d5f2335eab67/src/test/kotlin/fi/hsl/jore4/timetables/config/TestDatabaseProperties.kt#L6)):*
> ```Kotlin
> 
> @ConfigurationProperties(prefix = "jore4.test.db")
> data class TestDatabaseProperties(
> ```

I would rename this to `DataInserterProperties` to indicate that this is needed for test data population.
___
*[`src/test/resources/application-test.properties` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13#-Nh62YRe-v8SbETwTfbx:-Nh62YRe-v8SbETwTfby:b9c7gap) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/a195b3bc9d74117a7d4403daec62d5f2335eab67/src/test/resources/application-test.properties#L1)):*
> ```INI
> jore4.test.db.username=dbhasura
> ```

I would replace `jore4.test` prefix with `dataInserter`.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13#-Nh62JSb9Lqmypf9eQWz:-Nh62JSb9Lqmypf9eQX-:bv29ir8) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/a195b3bc9d74117a7d4403daec62d5f2335eab67/src/test/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt#L18)):*
> ```Kotlin
> @EnableConfigurationProperties(TestDatabaseProperties::class)
> class TimetablesDataInserterRunner(
>     val testDatabaseConfiguration: TestDatabaseProperties,
> ```

I think `dataInserterConfiguration` would be a better name.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13)* status: all files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/config/TestDatabaseProperties.kt` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13#-Nh622o63BSSHyR3_LCz:-Nh6ASzx0nfWlnI_dtN2:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/a195b3bc9d74117a7d4403daec62d5f2335eab67/src/test/kotlin/fi/hsl/jore4/timetables/config/TestDatabaseProperties.kt#L6)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would rename this to `DataInserterProperties` to indicate that this is needed for test data population.
</blockquote></details>

Done.
___
*[`src/test/resources/application-test.properties` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13#-Nh62YRe-v8SbETwTfbx:-Nh6ARt_3nmQut45tqEx:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/a195b3bc9d74117a7d4403daec62d5f2335eab67/src/test/resources/application-test.properties#L1)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would replace `jore4.test` prefix with `dataInserter`.
</blockquote></details>

Done.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13#-Nh62JSb9Lqmypf9eQWz:-Nh6AScP5bzdCenDxrv_:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/a195b3bc9d74117a7d4403daec62d5f2335eab67/src/test/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt#L18)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think `dataInserterConfiguration` would be a better name.
</blockquote></details>

Done.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt` line 58 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13#-Nh6F5Y720kpYu4xZVJa:-Nh6F5Y720kpYu4xZVJb:b-o6ldoj) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/e5b29a9fa0644495c7219e858b36c124b64099e9/src/test/kotlin/fi/hsl/jore4/timetables/service/TimetablesDataInserterRunner.kt#L58)):*
> ```Kotlin
>             "--port ${jdbcUri.port}",
>             "--database $databaseName",
>             "--user ${dataInerterDatabaseConfiguration.username}",
> ```

Typo, should be `dataInserter`

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13#-Nh6Fn_n8fnHJNrUm6SX):*
Typo, should be "application"

**Review by jarkkoka — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/13#-:-Nh6G8TDB1h8go6HMlCm:bg7igkv)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @culka)

**Pull request merged**
