### PR TITLE
Add GET API for fetching combine target frame

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22)* status: all files reviewed, 9 unresolved discussions (waiting on @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 134 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZoIJ04ceSNAFDyjOq:-NlZoIJ04ceSNAFDyjOr:b-kozrzr) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L134)):*
> ```Kotlin
> 
>         val targetPriorityEnumResult = runCatching { TimetablesPriority.fromInt(targetPriority) }
>         if (targetPriorityEnumResult.isFailure) {
> ```

This snippet of code does not look like idiomatic Kotlin.

I really would like to change the implementation of `TimetablesPriority.fromInt` into this form:

```kotlin
fun fromInt(value: Int): TimetablesPriority? = values().firstOrNull { it.value == value }
```

Then, you could implement this in a much more elegant way:

```kotlin
val targetPriorityEnum =  
    TimetablesPriority.fromInt(targetPriority)  
        ?: throw TargetPriorityParsingException("Failed to parse target priority", targetPriority)  
  
val targetVehicleScheduleFrame = combineTimetablesService.fetchTargetVehicleScheduleFrame(  
    stagingVehicleScheduleFrameId,  
    targetPriorityEnum  
)
```
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt` line 19 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZpGnH0WBOAyZ8Wxjk:-NlZpGnH0WBOAyZ8Wxjl:b-ngf84w) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt#L19)):*
> ```Kotlin
> 
>     // Not required by Hasura, but we want to always pass one.
>     val type: HasuraErrorType
> ```

See my comments related to this in another PR.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorType.kt` line 3 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZpJRk7-iSKOaPwhyD:-NlZpJRk7-iSKOaPwhyE:b-jlur4u) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorType.kt#L3)):*
> ```Kotlin
> package fi.hsl.jore4.timetables.api.util
> 
> enum class HasuraErrorType {
> ```

See my comments related to the name of this enum class in another PR.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt` line 41 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZsT2Q9JW4fjko0Gjj:-NlZsT2Q9JW4fjko0Gjk:be23sye) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt#L41)):*
> ```Kotlin
>     )
>     private val defaultToCombineTargetId = defaultTargetFrame.vehicleScheduleFrameId
>     private fun executeToCombineTimetablesRequest(
> ```

Please add line break before a function definition.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt` line 61 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZsv3B7WpCtCckjYX4:-NlZsv3B7WpCtCckjYX5:bdki2dq) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt#L61)):*
> ```Kotlin
>             combineTimetablesService.fetchTargetVehicleScheduleFrame(
>                 stagingVehicleScheduleFrameId,
>                 TimetablesPriority.fromInt(targetPriority)
> ```

Be explicit here:

```kotlin
TimetablesPriority.TEMPORARY
```
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt` line 65 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZtGYh1YIkD3KNcOZ9:-NlZtGYh1YIkD3KNcOZA:bys41qa) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt#L65)):*
> ```Kotlin
>         } answers { defaultTargetFrame }
> 
>         executeToCombineTimetablesRequest(stagingVehicleScheduleFrameId, targetPriority)
> ```

You could add this line to the beginning of the method:

```kotlin
val targetPriority = TimetablesPriority.TEMPORARY
```

Then you reference the `int` value here by:

```kotlin
targetPriority.value
```

It really is unnecessary to test parsing done in `TimetablesPriority.fromInt` here.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt` line 82 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZt7ByDpypDavX6yxG:-NlZt7ByDpypDavX6yxH:bdki2dq) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt#L82)):*
> ```Kotlin
>             combineTimetablesService.fetchTargetVehicleScheduleFrame(
>                 stagingVehicleScheduleFrameId,
>                 TimetablesPriority.fromInt(targetPriority)
> ```

Be explicit here:

```kotlin
TimetablesPriority.TEMPORARY
```
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/util/TransactionSystemExtensionsTest.kt` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZu1SM-nZ3A7Khr6YY:-NlZu1SM-nZ3A7Khr6YZ:b-npguaz) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/test/kotlin/fi/hsl/jore4/timetables/api/util/TransactionSystemExtensionsTest.kt#L10)):*
> ```Kotlin
> 
>     private fun createTransactionSystemExceptionWithCause(message: String): TransactionSystemException {
>         return TransactionSystemException("test exception", Exception(message))
> ```

The method body could be simplified to expression form:

```kotlin
private fun createTransactionSystemExceptionWithCause(message: String) =  
    TransactionSystemException("test exception", Exception(message))
```

No need to duplicate the return type.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 366 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZutTmBj9Q-zY6Yl0d:-NlZutTmBj9Q-zY6Yl0e:b-d6wu3c) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L366)):*
> ```Kotlin
>             val causeMessage = exception?.cause?.message
>             assertNotNull(causeMessage)
>             assertContains(causeMessage, "ERROR: conflicting schedules detected: vehicle schedule frame")
> ```

My current favourite to write this is:

```kotlin
assertFailsWith<TransactionSystemException> {  
    combineTimetablesService.combineTimetables(  
        listOf(stagingFrameId),  
        TimetablesPriority.STANDARD  
    )  
}.also { exception ->  
    // Check that the error messages are somewhat in the format we expect. TransactionSystemExtensions depends on these.  
    assertEquals(exception.message, "JDBC commit failed")  
  
    val causeMessage = exception.cause?.message  
    assertNotNull(causeMessage)  
    assertContains(causeMessage, "ERROR: conflicting schedules detected: vehicle schedule frame")  
    assertContains(causeMessage, "Where: PL/pgSQL function vehicle_schedule.validate_queued_schedules_uniqueness()")  
    assertContains(causeMessage, "SQL statement \"SELECT vehicle_schedule.validate_queued_schedules_uniqueness()")  
}
```

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22)* status: all files reviewed, 9 unresolved discussions (waiting on @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 134 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZoIJ04ceSNAFDyjOq:-NlbtfDl1-GWz_OVcVY5:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L134)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This snippet of code does not look like idiomatic Kotlin.

I really would like to change the implementation of `TimetablesPriority.fromInt` into this form:

```kotlin
fun fromInt(value: Int): TimetablesPriority? = values().firstOrNull { it.value == value }
```

Then, you could implement this in a much more elegant way:

```kotlin
val targetPriorityEnum =  
    TimetablesPriority.fromInt(targetPriority)  
        ?: throw TargetPriorityParsingException("Failed to parse target priority", targetPriority)  
  
val targetVehicleScheduleFrame = combineTimetablesService.fetchTargetVehicleScheduleFrame(  
    stagingVehicleScheduleFrameId,  
    targetPriorityEnum  
)
```
</blockquote></details>

Done.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt` line 65 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZtGYh1YIkD3KNcOZ9:-Nlb9cAdDNRaR1o43XBD:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesToCombineApiTest.kt#L65)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You could add this line to the beginning of the method:

```kotlin
val targetPriority = TimetablesPriority.TEMPORARY
```

Then you reference the `int` value here by:

```kotlin
targetPriority.value
```

It really is unnecessary to test parsing done in `TimetablesPriority.fromInt` here.
</blockquote></details>

Done.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt` line 366 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-NlZutTmBj9Q-zY6Yl0d:-NlbpS8u6qaUDlSAvOUM:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/570735fbfec2b679bdd70f6b24e872309d0d0794/src/test/kotlin/fi/hsl/jore4/timetables/service/CombineTimetablesServiceTest.kt#L366)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

My current favourite to write this is:

```kotlin
assertFailsWith<TransactionSystemException> {  
    combineTimetablesService.combineTimetables(  
        listOf(stagingFrameId),  
        TimetablesPriority.STANDARD  
    )  
}.also { exception ->  
    // Check that the error messages are somewhat in the format we expect. TransactionSystemExtensions depends on these.  
    assertEquals(exception.message, "JDBC commit failed")  
  
    val causeMessage = exception.cause?.message  
    assertNotNull(causeMessage)  
    assertContains(causeMessage, "ERROR: conflicting schedules detected: vehicle schedule frame")  
    assertContains(causeMessage, "Where: PL/pgSQL function vehicle_schedule.validate_queued_schedules_uniqueness()")  
    assertContains(causeMessage, "SQL statement \"SELECT vehicle_schedule.validate_queued_schedules_uniqueness()")  
}
```
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 27 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 55 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22#-Nlc8oHBAmGv0hZDrWtQ:-Nlc8oHC8TnGm6d_Bhcu:b-jts3qo) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/fab81b40789fc60bfe0ea049961b4eaa17a7d9a6/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L55)):*
> ```Kotlin
>     )
> 
>     private fun parseTargetPriority(targetPriority: Int) = TimetablesPriority.fromInt(targetPriority)
> ```

Since this method is essentially stateless (static) it should be located in a companion object.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/22)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
