### PR TITLE
Add types to error responses

### PR DESCRIPTION
**Pull request by Leitsi**
Relates to https://github.com/HSLdevcom/jore4/issues/1584

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)

### CODE REVIEW

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)* status: 0 of 27 files reviewed, all discussions resolved

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt` line 135 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjHWrWWDS3kuzvOCkVG:-NjHWrWWDS3kuzvOCkVH:btuoahg) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/44a19c22fee8d4711f72962ec8dc951b77a20368/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt#L135)):*
> ```Kotlin
>             )
> 
>             return errorMatchingConditions.find { it.second() }?.first ?: HasuraErrorType.TransactionSystemError
> ```

Note: I initially implemented this with `when`, like so:

```
return when {  
   errorMessage.contains("passing times and their matching stop points must be in same order") -> HasuraErrorType.PassingTimeStopPointMatchingOrderError  
   errorMessage.contains("first passing time must not have arrival\_time set") -> HasuraErrorType.PassingTimeFirstArrivalTimeError  
   errorMessage.contains("last passing time must not have departure\_time set") -> HasuraErrorType.PassingTimeLastDepartureTimeError  
   errorMessage.contains("all passing time that are not first or last in the sequence must have both departure and arrival time defined") -> HasuraErrorType.PassingTimeNullError  
   errorMessage.contains("inconsistent journey\_pattern\_ref within vehicle journey, all timetabled\_passing\_times must reference same journey\_pattern\_ref as the vehicle\_journey") -> HasuraErrorType.PassingTimesMixedJourneyPatternRefsError  
   errorMessage.contains("validate\_queued\_schedules\_uniqueness") -> HasuraErrorType.ConflictingSchedulesError  
   errorMessage.contains("validate\_service\_sequential\_integrity") -> HasuraErrorType.SequentialIntegrityError  
   else \-> HasuraErrorType.TransactionSystemError  
}
```

What bothered me with that was that the resulting `HasuraErrorType` was at the end of each line. I think that hurt readability. So I implemented it with this `errorMatchingConditions ` approach instead, to move the error types to start of line. Let me know if you disagree or have better suggestions.

**Review by culka — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt` line 135 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjHWrWWDS3kuzvOCkVG:-NjI8yy279CwRZLD6zxb:b-qajpj) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/44a19c22fee8d4711f72962ec8dc951b77a20368/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt#L135)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Note: I initially implemented this with `when`, like so:

```
return when {  
   errorMessage.contains("passing times and their matching stop points must be in same order") -> HasuraErrorType.PassingTimeStopPointMatchingOrderError  
   errorMessage.contains("first passing time must not have arrival\_time set") -> HasuraErrorType.PassingTimeFirstArrivalTimeError  
   errorMessage.contains("last passing time must not have departure\_time set") -> HasuraErrorType.PassingTimeLastDepartureTimeError  
   errorMessage.contains("all passing time that are not first or last in the sequence must have both departure and arrival time defined") -> HasuraErrorType.PassingTimeNullError  
   errorMessage.contains("inconsistent journey\_pattern\_ref within vehicle journey, all timetabled\_passing\_times must reference same journey\_pattern\_ref as the vehicle\_journey") -> HasuraErrorType.PassingTimesMixedJourneyPatternRefsError  
   errorMessage.contains("validate\_queued\_schedules\_uniqueness") -> HasuraErrorType.ConflictingSchedulesError  
   errorMessage.contains("validate\_service\_sequential\_integrity") -> HasuraErrorType.SequentialIntegrityError  
   else \-> HasuraErrorType.TransactionSystemError  
}
```

What bothered me with that was that the resulting `HasuraErrorType` was at the end of each line. I think that hurt readability. So I implemented it with this `errorMatchingConditions ` approach instead, to move the error types to start of line. Let me know if you disagree or have better suggestions.
</blockquote></details>

Few suggestions. One is to use `SQL_ERROR_MESSAGE` constants or similar to move them away from these lines for a cleaner look.

You can also move the return value to the next line, like

```
return when {
    errorMessage.contains("passing times and their matching stop points must be in same order")
    -> HasuraErrorType.PassingTimeStopPointMatchingOrderError
    errorMessage.contains("first passing time must not have arrival\_time set")
    -> HasuraErrorType.PassingTimeFirstArrivalTimeError
    else
    -> HasuraErrorType.TransactionSystemError
```
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesCombineApiTest.kt` line 126 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjI06YK467pkzlj-GWG:-NjI06YK467pkzlj-GWH:b9eo8hz) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/44a19c22fee8d4711f72962ec8dc951b77a20368/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesCombineApiTest.kt#L126)):*
> ```Kotlin
> 
>     @Test
>     fun `throws a 409 when service transaction fails to commit`() {
> ```

The test name says it tests when a commit fails, yet tests for a specific case.

I think this should use a generic case like `TransactionSystemError`, or either rename test to when there is a conflicting schedule.
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt` line 134 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjI1rso7YxGjHn5CRlc:-NjI1rso7YxGjHn5CRld:b9eo8hz) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/44a19c22fee8d4711f72962ec8dc951b77a20368/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt#L134)):*
> ```Kotlin
> 
>     @Test
>     fun `throws a 409 when service transaction fails to commit`() {
> ```

The test name says it tests when a commit fails, yet tests for a specific case.

I think this should use a generic case like `TransactionSystemError`, or either rename test to when there is a conflicting schedule.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesCombineApiTest.kt` line 126 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjI06YK467pkzlj-GWG:-NjICRssDVzOCQR--wd-:b3afval) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/44a19c22fee8d4711f72962ec8dc951b77a20368/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesCombineApiTest.kt#L126)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

The test name says it tests when a commit fails, yet tests for a specific case.

I think this should use a generic case like `TransactionSystemError`, or either rename test to when there is a conflicting schedule.
</blockquote></details>

Chose to use one of the more specific errors rather than an unrecognized transaction error so we test that the type is picked up correctly as well. I don't think it makes sense to test for every possible `TransactionSystemError` here either, that's why I created the separate `TransactionSystemExtensionsTest` suite for those.

I could add separate tests for plain `TransactionSystemError` and some more specific type, but again I don't think that provides much value. The plain `TransactionSystemError` test wouldn't really cover anything that this current one or the `TransactionSystemExtensionsTest` don't cover.

Maybe just slap a comment here we're using a "subset" of transaction errors here to check that type is set correctly as well?

**Review by jarkkoka — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)* status: all files reviewed, 2 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt` line 135 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjHWrWWDS3kuzvOCkVG:-NjIGZvR3ezaZRQUyVWj:b-g627me) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/44a19c22fee8d4711f72962ec8dc951b77a20368/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt#L135)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Few suggestions. One is to use `SQL_ERROR_MESSAGE` constants or similar to move them away from these lines for a cleaner look.

You can also move the return value to the next line, like

```
return when {
    errorMessage.contains("passing times and their matching stop points must be in same order")
    -> HasuraErrorType.PassingTimeStopPointMatchingOrderError
    errorMessage.contains("first passing time must not have arrival\_time set")
    -> HasuraErrorType.PassingTimeFirstArrivalTimeError
    else
    -> HasuraErrorType.TransactionSystemError
```
</blockquote></details>

I'd refactor out redundant `errorMessage.contains(...)` structure,

**Review by culka — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesCombineApiTest.kt` line 126 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjI06YK467pkzlj-GWG:-NjMg3bd9TWOQ8FMANci:b4putsz) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/44a19c22fee8d4711f72962ec8dc951b77a20368/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesCombineApiTest.kt#L126)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Added the comment here and on the other similar test.
</blockquote></details>

:ok_hand: 
___
*[`src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt` line 134 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjI1rso7YxGjHn5CRlc:-NjMg7opCgghnBiGh6jq:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/44a19c22fee8d4711f72962ec8dc951b77a20368/src/test/kotlin/fi/hsl/jore4/timetables/api/TimetablesReplaceApiTest.kt#L134)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Solved in same way as the above comment in same issue.
</blockquote></details>

:+1:

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt` line 131 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjONm-xEYMNI0hsCVYx:-NjONm-xEYMNI0hsCVYy:bd9kbxf) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/5ef70c188deafd8b8f7907c08bcdad57f84c69e6/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt#L131)):*
> ```Kotlin
>                 HasuraErrorType.PassingTimeStopPointMatchingOrderError to "passing times and their matching stop points must be in same order",
>                 HasuraErrorType.PassingTimeFirstArrivalTimeError to "first passing time must not have arrival_time set",
>                 HasuraErrorType.PassingTimeLastDepartureTimeError to "last passing time must not have departure_time set",
> ```

This list could be held in a const member of companion object. Not needed to construct it all over again.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)* status: all files reviewed, 2 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt` line 135 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NjHWrWWDS3kuzvOCkVG:-NlZ8O6X5JDG7oru8SZM:b-v7gob2) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/44a19c22fee8d4711f72962ec8dc951b77a20368/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt#L135)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Refactored a bit but left this list + find approach. Mainly moved the `contains` check inside the `find` and replaced it with `in` operator. Also added a comment.
</blockquote></details>

Well done!
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NlZ3ppEEc8LCui2vXgT:-NlZ3ppEEc8LCui2vXgU:bv7utmy) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/5ef70c188deafd8b8f7907c08bcdad57f84c69e6/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt#L19)):*
> ```Kotlin
> 
>     // Not required by Hasura, but we want to always pass one.
>     val type: HasuraErrorType
> ```

I'd replace

"but we want to always pass one"

with

"but we want to provide one so that the UI can present nice detailed error messages".


To be clear, I would introduce another interface for the `type` property, since it's not related to Hasura. Also, the enum name is wrong IMO.

```kotlin
sealed interface HasuraErrorExtensions {

    // code must be 4xx
    val code: Int
}

sealed interface JoreErrorExtensions: HasuraErrorExtensions {

    // Not required by Hasura, but we want to always pass one.
    val type: HasuraErrorType
}

data class PlainStatusExtensions(
    override val code: Int,
    override val type: HasuraErrorType
) : JoreErrorExtensions {
...
```
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorType.kt` line 3 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NlZ4MajAwAWiTezNM6-:-NlZ4MajAwAWiTezNM60:bf7hes4) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/af2a0e5391cdadbc3f6efea79ba5ab1ba7ac959a/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorType.kt#L3)):*
> ```Kotlin
> package fi.hsl.jore4.timetables.api.util
> 
> enum class HasuraErrorType {
> ```

The name of this class is really bad. I'd like to rename it to "VehicleSchedulePersistenceErrorType" or something shorter but still descriptive.

These types of errors really have nothing to do with Hasura itself.

However, these are very well separated error cases. Props for that! :+1:

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)* status: 23 of 28 files reviewed, 2 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NlZ3ppEEc8LCui2vXgT:-NlarALp45L00HMa4OTZ:bkiv3mh) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/5ef70c188deafd8b8f7907c08bcdad57f84c69e6/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorExtensions.kt#L19)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'd replace

"but we want to always pass one"

with

"but we want to provide one so that the UI can present nice detailed error messages".


To be clear, I would introduce another interface for the `type` property, since it's not related to Hasura. Also, the enum name is wrong IMO.

```kotlin
sealed interface HasuraErrorExtensions {

    // code must be 4xx
    val code: Int
}

sealed interface JoreErrorExtensions: HasuraErrorExtensions {

    // Not required by Hasura, but we want to always pass one.
    val type: HasuraErrorType
}

data class PlainStatusExtensions(
    override val code: Int,
    override val type: HasuraErrorType
) : JoreErrorExtensions {
...
```
</blockquote></details>

:ok_hand: done. Did similar change for HasuraErrorResponse, so the `type` is still required in the API responses.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorType.kt` line 3 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-NlZ4MajAwAWiTezNM6-:-Nlas09pBOahzZ60gIQ7:b-qfrpto) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/af2a0e5391cdadbc3f6efea79ba5ab1ba7ac959a/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorType.kt#L3)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The name of this class is really bad. I'd like to rename it to "VehicleSchedulePersistenceErrorType" or something shorter but still descriptive.

These types of errors really have nothing to do with Hasura itself.

However, these are very well separated error cases. Props for that! :+1:
</blockquote></details>

Good point. Renamed, but to `TimetablesApiErrorType` instead. These don't necessarily have to do with persistence, see eg. `TargetPriorityParsingError`.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20)* status: all files reviewed, 2 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt` line 122 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-Nlb0pM2DDD7Wva4pD5t:-Nlb0pM2DDD7Wva4pD5u:b-bcwwsq) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/1218e7cd64cf79fd08c9dff4041cb49e5c3ccd49/src/main/kotlin/fi/hsl/jore4/timetables/api/TimetablesController.kt#L122)):*
> ```Kotlin
>     @ExceptionHandler(RuntimeException::class)
>     fun handleRuntimeException(ex: RuntimeException): ResponseEntity<JoreErrorResponse> {
>         val hasuraExtensions: JoreErrorExtensions = when (ex) {
> ```

Maybe `hasuraExtensions` -> `errorExtensions` would be better.
___
*[`src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorResponse.kt` line 4 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-timetables-api/20#-Nlb0itc1LTE0jVnSVR7:-Nlb0itc1LTE0jVnSVR8:b6obcrl) ([raw file](https://github.com/HSLdevcom/jore4-timetables-api/blob/1218e7cd64cf79fd08c9dff4041cb49e5c3ccd49/src/main/kotlin/fi/hsl/jore4/timetables/api/util/HasuraErrorResponse.kt#L4)):*
> ```Kotlin
> 
> // See https://hasura.io/docs/latest/actions/action-handlers/#returning-an-error-response
> open class HasuraErrorResponse(
> ```

As of now, the `open` could replaced by `sealed`.

**Pull request merged**
